version: '3.6'
services:
#############################################
  redis_json:
      container_name: redis_json_db
      image: redislabs/rejson:latest
      restart: always
      networks:
          - saar-network
      ports:
        - 6379:6379
#############################################
  immunai:
      container_name: redis_json_db
      image: redislabs/rejson:latest
      restart: always
      ports:
        - 5000:5000
      networks:
        - saar-network
      volumes:
        - ./objects:/app/objects
#############################################
networks:
    saar-network: