version: '3.6'
services:
###########################
    labos:
        container_name: labos
        image: labos:latest
        restart: always
        ports:
            - "5001:5001"
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - FLASK_APP=./customer/api/v1/main.py
                - FLASK_RUN_PORT=80
        networks:
            - labos-net
###########################
networks:
    labos-net: