project_id          = "snappy-sight-332507"
region              = "europe-west3"
zones               = ["europe-west3-a", "europe-west3-b", "europe-west3-c"]
name                = "gke-cluster"
machine_type        = "e2-medium"
min_count           = 1
max_count           = 3
disk_size_gb        = 10
service_account     = "888996088256-compute@developer.gserviceaccount.com"
