---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ service_name }}-migration"
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
			containers:
      - name: "{{ service_name }}-migration"
        image: "{{ docker_image_version }}"
        env: ""
        command: ""
        args: ""
      imagePullSecrets:
      - name: "{{ github_registry_secret_name | default('nosecretdevenv') }}" # default empty because it's not relevant for dev env
      restartPolicy: Never
  backoffLimit: 1