---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ service_name }}-secrets"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
data: