apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
  namespace: releai
spec:
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - name: server
          image: simple
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: simple
  namespace: releai
spec:
  selector:
    app: simple
  ports:
    - name: http
      port: 50001
      targetPort: 5000
---