---
- name: Task
  hosts: localhost
  tasks:
    - name: "Install nginx"
      community.docker.docker_compose:
        project_name: nginx
        definition:
          version: '3.6'
          services:
            web:
              image: nginx:latest
              ports:
                - "80:80"
              environment:
                - NGINX_HOST=localhost
                - NGINX_PORT=80
