name: run-tests
on:
  repository_dispatch:
    types:
      - build

jobs:
  build:
    name: from curl requests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I just ran all your tests!"
          echo "payload: ${{ github.event.client_payload.var1 }}"
