on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: saar-win/personal-projects/new_action@v2
        with:
          key_1: 'test_1'
          key_2: 'test_2'
          key_3: 'test_3'
          key_4: 'test_4'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"