on:
  push
  branches:
    - v2

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A POC wf
    steps:
#############################################################################################
      - name: Check out code
        uses: actions/checkout@v2
#############################################################################################
      - name: Hello world action step
        id: settings
        uses: saar-win/personal-projects/new_action@settings
        with:
          ACTIONS_ACCESS_USERNAME: ${{ secrets.ACTIONS_ACCESS_USERNAME }}
          ACTIONS_ACCESS_KEY: ${{ secrets.ACTIONS_ACCESS_KEY }}
#############################################################################################
      - name: Hello world action step
        id: print
        uses: saar-win/personal-projects/new_action@v2
        with:
          file: new_action/test.yml