on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
#############################################################################################
      - name: Check out code
        uses: actions/checkout@v2
#############################################################################################
      - name: test
        id: hello_world_step
        run: |
          cd $GITHUB_WORKSPACE/new_action && echo "::set-output name=test::$(cat obj.json | jq)"
#############################################################################################
      - name: Hello world action step
        id: hello
        uses: saar-win/personal-projects/new_action@v2
        with:
          key_1: ${{ steps.hello_world_step.outputs.test }}
        env:
          TEST: ${{ steps.hello_world_step.outputs.test }}
#############################################################################################
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"